---
version: '3'
services:
  go-hello:
    build: ./go-hello
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: hello
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 8888:8080
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: hello
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
volumes:
  db-data:
    driver: local
